# Generated by Django 5.2.8 on 2025-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinput',
            name='child_strengths',
            field=models.JSONField(blank=True, default=list, help_text='Selected strengths: Friendly, Curious, Good memory, Loves routines, Creative, Enjoys music, Enjoys numbers, Helpful, Hardworking, Fast learner, Other'),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='daily_living_notes',
            field=models.TextField(blank=True, help_text='Additional notes about daily living skills'),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='dressing_independence',
            field=models.CharField(blank=True, choices=[('INDEPENDENT', 'Dresses independently'), ('SOME_HELP', 'Needs some help'), ('FULL_HELP', 'Needs full help')], help_text="Child's dressing independence level", max_length=50),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='eating_independence',
            field=models.CharField(blank=True, choices=[('INDEPENDENT', 'Eats independently'), ('SOME_HELP', 'Needs some help'), ('FULL_HELP', 'Needs full help')], help_text="Child's eating independence level", max_length=50),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='motor_needs',
            field=models.JSONField(blank=True, default=list, help_text='Selected motor needs: Fine motor difficulty, Gross motor difficulty, Weakness, Easily tired'),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='prior_services',
            field=models.JSONField(blank=True, default=list, help_text='Selected prior services: Schooling, Speech Therapy, Occupational Therapy, Behavioral Therapy'),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='sleep_quality',
            field=models.CharField(blank=True, choices=[('SLEEPS_WELL', 'Sleeps well'), ('DIFFICULTY_FALLING_ASLEEP', 'Difficulty falling asleep'), ('WAKES_OFTEN', 'Wakes often')], help_text="Child's sleep patterns", max_length=50),
        ),
        migrations.AddField(
            model_name='parentinput',
            name='toilet_skills',
            field=models.CharField(blank=True, choices=[('FULLY_TRAINED', 'Fully trained'), ('NEEDS_REMINDERS', 'Needs reminders'), ('NEEDS_HELP', 'Needs help'), ('USES_DIAPERS', 'Uses diapers')], help_text="Child's toilet training level", max_length=50),
        ),
    ]
