# Generated by Django 5.2.8 on 2025-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parentinput_child_strengths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinput',
            name='child_strengths',
            field=models.JSONField(blank=True, default=list, help_text='Selected strengths'),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='daily_living_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='dressing_independence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='eating_independence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='motor_needs',
            field=models.JSONField(blank=True, default=list, help_text='Selected motor needs'),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='prior_services',
            field=models.JSONField(blank=True, default=list, help_text='Selected prior services'),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='sleep_quality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='parentinput',
            name='toilet_skills',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
