# Generated by Django 5.2.8 on 2025-12-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_parentinput_child_strengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinput',
            name='intake_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
