# Generated by Django 5.2.8 on 2025-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacherinput_intake_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='assessment_scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='assessment_status',
            field=models.CharField(choices=[('none', 'None'), ('for_assessment', 'For Assessment'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='child',
            name='enrollment_status',
            field=models.CharField(choices=[('none', 'None'), ('enrolled', 'Enrolled')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='intake_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
