# Generated by Django 5.2.8 on 2025-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_child_assessment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepts_new_assessments',
            field=models.BooleanField(default=True, help_text='Whether this specialist is currently accepting new assessment bookings.'),
        ),
        migrations.AddField(
            model_name='user',
            name='focus_areas',
            field=models.JSONField(blank=True, default=list, help_text="List of focus areas, e.g. ['Autism', 'Early Literacy', 'Behavior']."),
        ),
        migrations.AddField(
            model_name='user',
            name='specialist_bio',
            field=models.TextField(blank=True, help_text='Short parent-friendly description of experience and focus areas.'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialist_title',
            field=models.CharField(blank=True, help_text='e.g., Speech-Language Pathologist, Occupational Therapist', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional practice as a specialist.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
