# Generated by Django 5.2.8 on 2025-12-04 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_accepts_new_assessments_user_focus_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_requests', to='core.child')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_requests', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(limit_choices_to={'role': 'SPECIALIST'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assessment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child'], name='core_assess_child_i_76a137_idx'), models.Index(fields=['specialist'], name='core_assess_special_2ccd48_idx'), models.Index(fields=['status'], name='core_assess_status_6de558_idx')],
            },
        ),
    ]
